### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by patelliandrea** [patelliandrea/SEBC#1]

**Comment by patelliandrea** [comment]
2c298ea3c9507bf26766655590369897c14412d1

**Comment by patelliandrea** [comment]
2c298ea3c9507bf26766655590369897c14412d1

**Comment by mfernest** [comment]
Please leave lab issues open. It's easier for @jqnik and I to navigate these issues if you apply a `submitted` label. We'll review the work, add an `evaluated` label and then close the issue for you.

Also it looks like the labels we need aren't complete. Please review the instructions.
