### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by patelliandrea** [patelliandrea/SEBC#3]

**Comment by patelliandrea** [comment]
Done replication e3ee3c1dd09702133efc6797726ed5dd027614dc

Starting terasort

**Comment by patelliandrea** [comment]
Done testing HDFS performance e3b9a7ffaa1c5276c6278d593d6b8ebd40b5817d

Starting snapshots

**Comment by patelliandrea** [comment]
Done testing snapshots f9e0eb20db908ea0ef8f291d6e4f6adc7d43fc97

Enabling HA

**Comment by patelliandrea** [comment]
Finish enabling HA 8dbca161342b24295f81648f20de207d653502fd

**Comment by patelliandrea** [comment]
http://ec2-54-93-129-189.eu-central-1.compute.amazonaws.com:7180/ 
(http://54.93.129.189:7180)

**Comment by mfernest** [comment]
I really like logging the progress with commit codes. Too bad GitHub seems to be very slow at retrieving them.
